### ISSUE TITLE
TODO: List for myself

### ISSUE THREAD

**Issue by C0nw0nk** [C0nw0nk/Nginx-Lua-Anti-DDoS#29]
A TODO List of things i want to improve and have completed in improving. 👊

### Performance Optimizations

- [x] Remove `table.insert` Here you can see the performance i made the script gain by removing `table.insert` https://springrts.com/wiki/Lua_Performance#TEST_12:_Adding_Table_Items_.28table.insert_vs._.5B_.5D.29 If you think about millions of requests that is a huge impact.

- [x] Remove uses of `pairs` and `ipairs` in foreach loops to gain performance. https://springrts.com/wiki/Lua_Performance#TEST_9:_for-loops

- [ ] Replace `string.gsub` with `ngx.re.gsub` for cached regex uses Having serious issues with the last couple of instances in my script this is proving to be a night mare to use over `string.gsub`.
https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/blob/master/lua/anti_ddos_challenge.lua#L1432
https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/blob/master/lua/anti_ddos_challenge.lua#L1437

### Anti-DDoS Features

- [x] Limit connections / Max requests from an IP to a configurable number lets say 1000 requests a second can also set custom paths, domains, urls etc to protect with this. **Completed to be pushed out with update still I am going to finish the Auto feature before releasing this since it is all rolled up in one**. 

- [x] Finish building automated Anti-DDoS detection 10% complete so far.
Rather than manually having to turn the script on / off for certain sites file paths etc the script will have the inteligence to do it itself. Something Cloudflare and such companies also lack in is the ability to have this automated feature to them by the time your under attack its to late your site has been down for some time this feature will prevent the down time.

### Increase Web Application Firewall Features

- [x] IPv4 and IPv6 blocking and whitelisting including subnet ranges.

- [x] User-Agent blocking and whitelisting to block bad bots and exploits / scanners.

- [x] Add ability to inspect POST Data / Fields and block malicious POST requests / exploits.

- [x] Add ability to inspect URL for malicious content SQL/SQI Injections XSS attacks / exploits.

- [x] Add ability to inspect query strings and arguements for malicious content / exploits.

- [x] Add ability to inspect all Request Headers provided by the client connecting.

- [x] Add ability to inspect cookies for exploits.

### Caching Speed and Performance Features

- [x] Query String Sorting I was inspired by Cloudflare to build this feature and add it in it is a really useful cool and effective speed feature for all websites Cloudflares loss is that they charge people $3000 dollars for it what is a disgusting thing to do so i give it to you all for free. https://blog.cloudflare.com/increasing-cache-hit-rates-with-query-string-sort/ Added https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/ee2320e931dae9a38773b49ea957131ed700fb5d

- [x] Query String Whitelist Added https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/ee2320e931dae9a38773b49ea957131ed700fb5d

- [x] Query String Removal (It is a blacklist but it will just drop / remove the argument from the URL not block the request) Added https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/ee2320e931dae9a38773b49ea957131ed700fb5d

# Additional

- [ ] Cookie Consent EU Laws require a visible area notifying users of required cookies so can make it a feature to turn on or off and intercept all headers from nginx of cookies and not pass any cookie headers to users until they accept a consent cookie.

**Comment by chenluyong** [comment]
tks your opensource

**Comment by dwabs** [comment]
how can I contact you?

**Comment by venomone** [comment]
same here, any contact details would be awesome!

**Comment by C0nw0nk** [comment]
Added a additional feature currently working on to do with cookie consent so no nginx cookie headers will be sent to users browsers until they agree / consent to cookies.

**Comment by C0nw0nk** [comment]
TODO :  investigate NYI for Lua JIT and see what functions should be using `ngx.re.*` API's instead of `string.match gsub` etc.

https://api7.ai/learning-center/openresty/avoid-lua-not-yet-implemented-features

https://web.archive.org/web/20220717120825/http://wiki.luajit.org/NYI#libraries_string-library

**Comment by C0nw0nk** [comment]
Completed Automatic Under Attack Mode. Completed! https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/d40e9081939a22cc7c642f5ad4f4fbd380f2b3e7
